/**
 * TypeScript mirror of the names published in `styles/tokens.css`.
 *
 * tailwind-merge cannot read the CSS, so it needs this list to know that
 * `text-control` is a font size and `text-fg-muted` a colour. Without it a
 * class passed in through `className` would not override the component's own.
 *
 * Generated by hand from the CSS and kept honest by `tokens.test.ts`, which
 * compares the two files and fails the moment they drift apart.
 */

export const colorTokens = [
  'transparent',
  'current',
  'inherit',
  'white',
  'black',
  'canvas',
  'panel',
  'surface',
  'surface-raised',
  'surface-hover',
  'surface-active',
  'surface-selected',
  'surface-chip',
  'surface-disabled',
  'surface-floating',
  'surface-tooltip',
  'surface-inverse',
  'surface-brand',
  'surface-brand-hover',
  'border',
  'border-subtle',
  'border-divider',
  'border-muted',
  'border-raised',
  'border-field',
  'border-strong',
  'border-control',
  'border-tooltip',
  'border-brand',
  'fg',
  'fg-secondary',
  'fg-tertiary',
  'fg-muted',
  'fg-subtle',
  'fg-meta',
  'fg-ghost',
  'fg-placeholder',
  'fg-disabled',
  'fg-brand',
  'fg-on-brand',
  'fg-inverse',
  'fg-on-tooltip',
  'sev-error',
  'sev-error-fg',
  'sev-error-surface',
  'sev-warning',
  'sev-warning-fg',
  'sev-warning-surface',
  'sev-info',
  'sev-info-fg',
  'sev-info-surface',
  'danger',
  'danger-fg',
  'danger-surface',
  'success',
  'success-fg',
  'success-surface',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'chart-muted',
  'ring',
  'ring-subtle',
  'scrim',
] as const;

export const textTokens = [
  'page-title',
  'title',
  'section',
  'card-title',
  'body',
  'value',
  'control',
  'label',
  'meta',
  'hint',
  'code',
  'mono',
  'mono-sm',
  'column',
  'badge',
  'tag',
  'kbd',
  'numeric',
  'numeric-lg',
] as const;

export const spacingTokens = [
  'control-xs',
  'control-sm',
  'control-md',
  'control-lg',
  'chip',
  'topbar',
  'wordmark',
  'subheader',
  'tab',
  'sidebar',
  'sidebar-rail',
  'nav-item',
  'rail-item',
  'rail-item-w',
  'project-card',
  'menu-item',
  'row',
  'row-head',
  'page-gutter',
  'search',
  'avatar',
  'avatar-lg',
  'badge',
  'dot',
  'icon-xs',
  'icon-sm',
  'icon-md',
  'icon-lg',
  'icon-xl',
  'icon-2xl',
] as const;

export const radiusTokens = [
  '2xs',
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
  'pill',
] as const;

export const durationTokens = [
  'instant',
  'fast',
  'moderate',
  'slow',
  'deliberate',
] as const;

export const easeTokens = ['linear', 'standard', 'entrance', 'exit'] as const;

export const shadowTokens = ['raised', 'tooltip', 'overlay', 'dialog'] as const;

export const fontTokens = ['sans', 'mono'] as const;

export type ColorToken = (typeof colorTokens)[number];
export type TextToken = (typeof textTokens)[number];
export type SpacingToken = (typeof spacingTokens)[number];
export type RadiusToken = (typeof radiusTokens)[number];
export type DurationToken = (typeof durationTokens)[number];
export type EaseToken = (typeof easeTokens)[number];
export type ShadowToken = (typeof shadowTokens)[number];
export type FontToken = (typeof fontTokens)[number];
