/**
 * @rustrak/client - TypeScript client for Rustrak API
 *
 * A type-safe, fully-featured client for interacting with Rustrak error tracking API.
 *
 * @packageDocumentation
 */

// Main client
export { RustrakClient } from './client.js';

// Configuration
export type { ClientConfig } from './config.js';
// Errors
export {
  AuthenticationError,
  AuthorizationError,
  BadRequestError,
  NetworkError,
  NotFoundError,
  RateLimitError,
  RustrakError,
  ServerError,
  ValidationError,
} from './errors/index.js';
// Types
export type {
  AcceptInvitation,
  ActivityEntry,
  AlertHistory,
  AlertIntegration,
  AlertRule,
  AlertRuleChannelInput,
  AlertStatus,
  AlertType,
  ApiError,
  AssembleInput,
  AssembleResponse,
  AuthResponse,
  AuthToken,
  AuthTokenCreated,
  BulkDeleteIssues,
  BulkUpdateIssues,
  /** @deprecated Use ProviderType */
  ChannelType,
  ChunkUploadCapability,
  CleanupCounts,
  CleanupOptions,
  CreateAlertIntegration,
  CreateAlertRule,
  CreateAuthToken,
  CreateComment,
  CreateDeploy,
  CreateInvitation,
  /** @deprecated Use CreateAlertIntegration */
  CreateNotificationChannel,
  CreateProject,
  CreateUserReport,
  Event,
  EventDetail,
  GlobalRole,
  Invitation,
  InvitationInfo,
  Issue,
  IssueAggregates,
  IssueFilter,
  IssueHash,
  IssuePriority,
  IssueSort,
  IssueStats,
  IssueStatsWindow,
  IssueStatus,
  IssueTagValue,
  ListAlertHistoryOptions,
  ListEventsOptions,
  ListIssuesOptions,
  ListLogsOptions,
  ListProjectsOptions,
  ListSourceMapsResponse,
  ListTransactionsOptions,
  Log,
  LoginRequest,
  LoginResult,
  /** @deprecated Use AlertIntegration */
  NotificationChannel,
  OffsetPaginatedResponse,
  PaginatedResponse,
  Project,
  ProjectMember,
  ProjectRole,
  ProjectStorage,
  ProviderType,
  RegisterRequest,
  ReleaseHealth,
  ReleaseHealthRow,
  RoutingOverride,
  ServerVersion,
  SortOrder,
  SourceMapFile,
  SourceMapGcResult,
  SourceMapStorage,
  Span,
  StorageSummary,
  TagSummary,
  TagValueCount,
  TeamMember,
  TestChannelResponse,
  TestIntegrationBody,
  Transaction,
  TransactionDetail,
  TransactionStats,
  UpdateAlertIntegration,
  UpdateAlertRule,
  UpdateIssueState,
  /** @deprecated Use UpdateAlertIntegration */
  UpdateNotificationChannel,
  UpdateProject,
  UpdateUserRole,
  UpsertProjectMember,
  User,
  UserReport,
} from './types/index.js';
